Repository manytask/checker, pull requests merged in 2023-10, with the labels that each got.

#32 feat: Detect changes using filesystem
  checker/actions/grade.py
  checker/testers/cpp.py
  checker/testers/python.py
  checker/utils/files.py
  checker/utils/git.py
  tests/course/test_config.py
  tests/examples/test_course_configs.py
  tests/executors/test_sandbox.py
  tests/testers/test_cpp.py
  tests/testers/test_tester.py
  tests/utils/test_files.py
  tests/utils/test_git.py
  tests/utils/test_manytask.py
  tests/utils/test_print.py
Labels: type: test, type: feature

#36 fix: remove --ignore-all-space in changes detection
  checker/utils/files.py
Labels: type: fix

#38 feat(testers): add external testers
  checker/__main__.py
  checker/course/config.py
  checker/testers/tester.py
  tests/testers/test_tester.py
Labels: type: test

#37 fix: export all files from root dir
  checker/actions/export.py
Labels: type: fix

#52 ci: check PR title
  .github/workflows/pr-title.yml
Labels: type: ci

#54 ci(pypi): use Trusted publishing
  .github/workflows/publish.yml
Labels: type: ci
