Repository manytask/checker, pull requests merged in 2024-01, with the labels that each got.

#84 feat: Required .task.yml and .group.yml files
  Makefile
  checker/__main__.py
  checker/configs/__init__.py
  checker/configs/checker.py
  checker/configs/deadlines.py
  checker/configs/task.py
  checker/course.py
  checker/exporter.py
  docs/1_getting_started.md
  docs/2_configuration.md
  tests/__init__.py
  tests/configs/__init__.py
  tests/conftest.py
  tests/plugins/__init__.py
  tests/test_conftest.py
  tests/test_course.py
  tests/test_exporter.py
Labels: feature

#85 ci: publish main docker and docs
  .github/workflows/publish.yml
  .github/workflows/test.yml
  Makefile
  docs/5_usage.md
Labels: documentation, ci

#87 feat: Ascii art tag
  checker/__main__.py
  checker/configs/deadlines.py
  checker/utils.py
  tests/test_utils.py
Labels: ci, feature

#86 ci: add platforms for docker build
  .github/workflows/publish.yml
  .github/workflows/test.yml
  Dockerfile
Labels: ci

#88 docs: add `!!! note tl;dr` to getting started
  docs/1_getting_started.md
Labels: documentation

#89 feat: add changes detection for `checker grade`
  Dockerfile
  checker/__main__.py
  checker/course.py
  docs/2_configuration.md
  pyproject.toml
  tests/test_course.py
Labels: feature

#90 feat: templates - `search`, `create` or `search_or_create`
  checker/__main__.py
  checker/configs/checker.py
  checker/course.py
  checker/exporter.py
  docs/1_getting_started.md
  tests/test_course.py
  tests/test_exporter.py
Labels: feature

#82 feat(plugin): add sandbox plugin
  .github/workflows/test.yml
  Dockerfile
  checker/plugins/firejail.py
  checker/plugins/scripts.py
  tests/conftest.py
  tests/plugins/test_firejail.py
Labels: feature

#94 feat: deadlines -> manytask config
  Makefile
  checker/__main__.py
  checker/configs/__init__.py
  checker/configs/manytask.py
  checker/course.py
  docs/0_concepts.md
  docs/1_getting_started.md
  docs/2_configuration.md
  tests/test_course.py
  tests/test_exporter.py
Labels: feature

#95 feat: change deadlines config
  checker/configs/manytask.py
  checker/course.py
  checker/exporter.py
  tests/configs/test_manytask.py
  tests/test_course.py
  tests/test_exporter.py
Labels: feature
